import { StyleSheet } from "react-native";

export const countryStyles = StyleSheet.create({
  mainContainer: { flex: 1, backgroundColor: "#0f172a" },
  centerContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#0f172a",
  },
  errorText: {
    fontSize: 14,
    fontWeight: "900",
    color: "#ef4444",
    marginBottom: 16,
    letterSpacing: 1,
  },
  backButton: {
    backgroundColor: "#334155",
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 20,
  },
  backButtonText: {
    color: "#ffffff",
    fontWeight: "bold",
    fontSize: 12,
    letterSpacing: 0.5,
  },

  headerContainer: {
    backgroundColor: "#1e293b",
    paddingVertical: 18,
    paddingHorizontal: 24,
    borderBottomWidth: 1,
    borderColor: "#334155",
    alignItems: "center",
    position: "relative",
  },
  headerBackButton: { position: "absolute", left: 24, top: 22 },
  headerBackButtonText: {
    fontSize: 12,
    color: "#0ea5e9",
    fontWeight: "900",
    letterSpacing: 0.5,
  },
  titleRow: { flexDirection: "row", alignItems: "center", gap: 14 },
  headerTitle: {
    fontSize: 20,
    fontWeight: "900",
    color: "#ffffff",
    letterSpacing: 0.5,
  },
  headerSubtitle: {
    fontSize: 11,
    color: "#64748b",
    marginTop: 6,
    fontWeight: "800",
    letterSpacing: 1,
  },

  filterRow: {
    flexDirection: "row",
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: "#0f172a",
    gap: 8,
    justifyContent: "center",
    borderBottomWidth: 1,
    borderColor: "#1e293b",
  },
  filterBtn: {
    paddingVertical: 8,
    paddingHorizontal: 14,
    borderRadius: 20,
    backgroundColor: "#1e293b",
    borderWidth: 1,
    borderColor: "#334155",
  },
  filterBtnActive: {
    backgroundColor: "rgba(14, 165, 233, 0.15)",
    borderColor: "#0ea5e9",
  },
  filterText: {
    color: "#64748b",
    fontSize: 11,
    fontWeight: "900",
    letterSpacing: 0.5,
  },
  filterTextActive: { color: "#0ea5e9" },

  emptyStateContainer: { paddingTop: 60, alignItems: "center" },
  emptyStateText: {
    color: "#475569",
    fontSize: 14,
    fontWeight: "900",
    letterSpacing: 1,
  },

  gridContainer: { padding: 8, paddingBottom: 110 },
  stickerContainer: {
    flex: 1,
    margin: 6,
    height: 84,
    borderRadius: 12,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    position: "relative",
    maxWidth: "22%",
  },
  stickerCountryCode: {
    fontSize: 9,
    fontWeight: "900",
    opacity: 0.6,
    letterSpacing: 1,
  },
  stickerNumber: {
    fontSize: 22,
    fontWeight: "bold",
    marginTop: 2,
    letterSpacing: -0.5,
  },

  badgeContainer: {
    position: "absolute",
    top: -6,
    right: -6,
    backgroundColor: "#ef4444",
    borderRadius: 10,
    paddingHorizontal: 6,
    height: 18,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 2,
    borderColor: "#0f172a",
  },
  badgeText: { color: "#ffffff", fontSize: 9, fontWeight: "900" },

  floatingScanButton: {
    position: "absolute",
    bottom: 30,
    alignSelf: "center",
    backgroundColor: "#0ea5e9",
    paddingVertical: 16,
    paddingHorizontal: 40,
    borderRadius: 30,
    elevation: 8,
    shadowColor: "#0ea5e9",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 8,
  },
  floatingScanButtonText: {
    color: "#ffffff",
    fontSize: 15,
    fontWeight: "900",
    letterSpacing: 1,
  },
});
